# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVH4m5MnO38K4OjG_wHBsbMWED-WgV-K

# SWIGGY SALES ANALYSIS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_excel("swiggy_data.xlsx")

df.head()

df.shape[0]

print("no. of fields:", df.shape[1])

df.info

"""DATA Types"""

df.dtypes

df.describe()

"""# KPI

Total Sales
"""

total_sales = df["Price (INR)"].sum()
print("Total sales (INR):",total_sales)

"""Average Rating"""

average_rating = df["Rating"].mean()
print("Average Rating:",round(average_rating,2))

"""Average Order Value"""

avg_order_value = df["Price (INR)"].mean()
print("Avg Order Value (INR):", round(avg_order_value,2))

"""Rating Count"""

rating_count = df["Rating Count"].sum()
print("ratings count:", round(rating_count,2))

"""Total Orders"""

total_orders = df["Order Date"].count()
print("total_orders:", round(total_orders,2))

"""# **CHARTS DESIGN**"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("swiggy_data.xlsx")

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["YearMonth"] = df["Order Date"].dt.to_period("M").astype(str)

monthly_revenue = df.groupby("YearMonth")["Price (INR)"].sum().reset_index()

plt.figure()
plt.plot(monthly_revenue["YearMonth"], monthly_revenue["Price (INR)"])
plt.xticks(rotation=45)
plt.xlabel("Month")
plt.ylabel("Total Sales (INR)")
plt.title("Monthly Sales Trend")
plt.tight_layout()
plt.show()

df["DayName"] = pd.to_datetime(df["Order Date"]).dt.day_name()

daily_revenue = (
    df.groupby("DayName")["Price (INR)"].sum().reindex(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
)
plt.figure(figsize=(10,5))
plt.bar(daily_revenue.index,daily_revenue.values)
plt.title("Daily Revenue Trend (Mon-Sun)")
plt.xlabel("Day")
plt.ylabel("Revenue (INR)")
plt.xticks(rotation=30)

plt.show()

non_veg_keywords = [
    "chicken", "egg","fish","mutton",
    "prawn","biryani","kabab","kebab",
    "non-veg","non-veg"
]
df["Food Category"] = np.where(
    df["Dish Name"].str.lower().str.contains("/".join(non_veg_keywords), na = False),
    "Non-Veg",
    "Veg"
)

import numpy as np

non_veg_keywords = [
    "chicken", "egg","fish","mutton",
    "prawn","biryani","kabab","kebab",
    "non-veg"
]

df["Food Category"] = np.where(
    df["Dish Name"].str.lower().str.contains("|".join(non_veg_keywords), na=False),
    "Non-Veg",
    "Veg"
)

food_revenue = (
    df.groupby("Food Category")["Price (INR)"]
    .sum()
    .reset_index()
)

fig = px.pie(
    food_revenue,
    values="Price (INR)",
    names="Food Category",
    hole=0.5,
    title="Revenue Contribution: Veg vs Non-Veg",
)

fig.update_traces(
    textinfo="percent+label",
    pull=[0.05, 0]
)

fig.update_layout(
    height = 500,
    margin=dict(t=60,b=40,l=40,r=40)
)

fig.show()

"""# Total Sales by State"""

fig = px.bar(
    df.groupby("State", as_index=False)["Price (INR)"].sum()
    .sort_values("Price (INR)", ascending=False),
    x="Price (INR)",
    y="State",
    orientation="h",
    title="Revenue by State (INR)"
)

fig.update_layout(height=600, yaxis=dict(autorange="reversed"))
fig.show()

"""# Top 5 Cities by Sales"""

top_5_cities = df.groupby("City")["Price (INR)"] \
               .sum() \
               .nlargest(5) \
               .sort_values() \
               .reset_index()

fig = px.bar(
    top_5_cities,
    x ="Price (INR)",
    y = "City",
    orientation ="h",
    title="Top 5 cities by sales (INR)",
    color_discrete_sequence=["red"]
)

fig.show()